/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApiKeys {
  'elevenLabsKey' : [] | [string],
  'preferredVoiceId' : [] | [string],
}
export interface Project {
  'id' : string,
  'title' : string,
  'script' : string,
  'createdAt' : bigint,
  'segments' : Array<Segment>,
}
export interface ProjectSummary {
  'id' : string,
  'title' : string,
  'createdAt' : bigint,
}
export interface Segment {
  'text' : string,
  'brollKeywords' : Array<string>,
  'index' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TtsRequest { 'voiceId' : string, 'script' : string }
export interface TtsResponse { 'audio' : string, 'error' : [] | [string] }
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'deleteProject' : ActorMethod<[string], undefined>,
  'generateTts' : ActorMethod<[TtsRequest], TtsResponse>,
  'getApiKeys' : ActorMethod<[], ApiKeys>,
  'getProject' : ActorMethod<[string], Project>,
  'listProjects' : ActorMethod<[], Array<ProjectSummary>>,
  'saveApiKeys' : ActorMethod<[[] | [string], [] | [string]], undefined>,
  'saveProject' : ActorMethod<
    [string, string, string, Array<Segment>],
    undefined
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];