/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TtsRequest = IDL.Record({
  'voiceId' : IDL.Text,
  'script' : IDL.Text,
});
export const TtsResponse = IDL.Record({
  'audio' : IDL.Text,
  'error' : IDL.Opt(IDL.Text),
});
export const ApiKeys = IDL.Record({
  'elevenLabsKey' : IDL.Opt(IDL.Text),
  'preferredVoiceId' : IDL.Opt(IDL.Text),
});
export const Segment = IDL.Record({
  'text' : IDL.Text,
  'brollKeywords' : IDL.Vec(IDL.Text),
  'index' : IDL.Nat,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'script' : IDL.Text,
  'createdAt' : IDL.Int,
  'segments' : IDL.Vec(Segment),
});
export const ProjectSummary = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'generateTts' : IDL.Func([TtsRequest], [TtsResponse], []),
  'getApiKeys' : IDL.Func([], [ApiKeys], ['query']),
  'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(ProjectSummary)], ['query']),
  'saveApiKeys' : IDL.Func([IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)], [], []),
  'saveProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Segment)],
      [],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TtsRequest = IDL.Record({ 'voiceId' : IDL.Text, 'script' : IDL.Text });
  const TtsResponse = IDL.Record({
    'audio' : IDL.Text,
    'error' : IDL.Opt(IDL.Text),
  });
  const ApiKeys = IDL.Record({
    'elevenLabsKey' : IDL.Opt(IDL.Text),
    'preferredVoiceId' : IDL.Opt(IDL.Text),
  });
  const Segment = IDL.Record({
    'text' : IDL.Text,
    'brollKeywords' : IDL.Vec(IDL.Text),
    'index' : IDL.Nat,
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'script' : IDL.Text,
    'createdAt' : IDL.Int,
    'segments' : IDL.Vec(Segment),
  });
  const ProjectSummary = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'generateTts' : IDL.Func([TtsRequest], [TtsResponse], []),
    'getApiKeys' : IDL.Func([], [ApiKeys], ['query']),
    'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(ProjectSummary)], ['query']),
    'saveApiKeys' : IDL.Func([IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)], [], []),
    'saveProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Segment)],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };